#!/bin/bash
$change="$1"

[[ $change -ne c ]] && apt install -y socat wakeonlan nut git python3-rpi.gpio && echo "Ensure that GPIO is enable in raspi-config" && git clone https://github.com/brendenhoffman/PiPower.git

cp -r /home/pi/PiPower/pipower /etc/pipower
cp /home/pi/PiPower/pipower.service /etc/systemd/system/pipower.service
chmod +x /home/pi/PiPower/pipower-*
cp /home/pi/PiPower/pipower-* /bin/

[ $change -eq c ] && systemctl daemon-reload && systemctl stop pipower
systemctl start pipower
systemctl enable pipower
