#!/bin bash

apt install -y socat wakeonlan nut git

git clone https://github.com/brendenhoffman/PiPower.git
mv PiPower/maclist /etc/maclist
mv PiPower/pipower.service /etc/systemd/system/pipower.service
chmod +x PiPower/*
mv PiPower/pipower* /bin/

systemctl start pipower
